### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by liujun1209** [shen0834/wangyue-learngit#2]
I can't find the class PinchToZoomDraweeView at line 75

PinchToZoomDraweeView.this.postDelayed(new AutoRunableZoom(newScale), 16);

**Comment by shen0834** [comment]
PinchToZoomDraweeView.this.postDelayed(new AutoRunableZoom(newScale), 16);

sorry,i forget change the name,
should be:SimplePhotoView.this.postDelayed(new AutoRunableZoom(newScale), 16);

**Comment by liujun1209** [comment]
ok, thanks
